# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'golden' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for golden keystore

  node_modules_path = '../node_modules'
  rn_path = "../node_modules/react-native"
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTCameraRoll',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  pod 'react-native-golden-keystore', path: '../Libs/react-native-golden-keystore'
  # End pods for golden keystore
  
  pod 'react-native-camera', path: "#{node_modules_path}/react-native-camera"
  pod 'ReactNativeFabric', path: "#{node_modules_path}/react-native-fabric"
  pod 'react-native-fcm', path: "#{node_modules_path}/react-native-fcm"
  pod 'rn-golden-loading', path: '../Libs/rn-golden-loading'

  
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Core'

  pod 'react-native-shimmer', :path => "#{node_modules_path}/react-native-shimmer"

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)
      
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end    
  end
end


